config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/EPrints-OAPiwik:
      branch: master
      repo: https://github.com/openaire/EPrints-OAPiwik
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/EPrints-OAPiwik git:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_perky_cassowary.sh
        container: qc.acc_pumpkin_meticulous_chameleon
  QC.Doc:
    repos:
      github.com/openaire/EPrints-OAPiwik find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goldenrod_tactful_antelope.sh
        container: qc.doc_clove_perky_catfish
      github.com/openaire/EPrints-OAPiwik git:
        commands:
        - /usr/bin/env sh .sqa/script.cayenne_resourceful_mink.sh
        container: qc.doc_marina_candid_porpoise
      github.com/openaire/EPrints-OAPiwik markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.glaucous_ambitious_heron.sh
        container: qc.doc_forest_understanding_dolphin
  QC.Lic:
    repos:
      github.com/openaire/EPrints-OAPiwik licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snow_tolerant_lobster.sh
        container: qc.lic_thunder_humorous_reindeer
  QC.Ver:
    repos:
      github.com/openaire/EPrints-OAPiwik get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goldenrod_joyful_chinchilla.sh
        container: qc.ver_isabelline_spontaneous_pelican
timeout: 5400
