config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/EPrints-OAPiwik:
      branch: master
      repo: https://github.com/openaire/EPrints-OAPiwik
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/EPrints-OAPiwik git:
        commands:
        - /usr/bin/env sh .sqa/script.bone_vigilant_porpoise.sh
        container: qc.acc_cosmos_exuberant_mandrill
  QC.Doc:
    repos:
      github.com/openaire/EPrints-OAPiwik find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.rose_gracious_ibex.sh
        container: qc.doc_isabelline_radiant_parrot
      github.com/openaire/EPrints-OAPiwik git:
        commands:
        - /usr/bin/env sh .sqa/script.teal_inspired_boar.sh
        container: qc.doc_linen_stoic_spren
      github.com/openaire/EPrints-OAPiwik markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluebell_forgiving_stingray.sh
        container: qc.doc_marigold_lucky_heron
  QC.Lic:
    repos:
      github.com/openaire/EPrints-OAPiwik licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tundra_vibrant_quokka.sh
        container: qc.lic_storm_intuitive_tiger
  QC.Ver:
    repos:
      github.com/openaire/EPrints-OAPiwik get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.linen_playful_salamander.sh
        container: qc.ver_blush_methodical_peacock
timeout: 5400
