config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/EPrints-OAPiwik:
      branch: master
      repo: https://github.com/openaire/EPrints-OAPiwik
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/EPrints-OAPiwik git:
        commands:
        - /usr/bin/env sh .sqa/script.turmeric_zany_manta.sh
        container: qc.acc_cardamom_carefree_boa
  QC.Doc:
    repos:
      github.com/openaire/EPrints-OAPiwik find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ice_grateful_vulture.sh
        container: qc.doc_alabaster_brilliant_elephant
      github.com/openaire/EPrints-OAPiwik git:
        commands:
        - /usr/bin/env sh .sqa/script.ginger_humble_eagle.sh
        container: qc.doc_cobalt_resilient_otter
      github.com/openaire/EPrints-OAPiwik markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boysenberry_pensive_ibex.sh
        container: qc.doc_byzantium_stoic_dhole
  QC.Lic:
    repos:
      github.com/openaire/EPrints-OAPiwik licensee:
        commands:
        - /usr/bin/env sh .sqa/script.orchid_reliable_newt.sh
        container: qc.lic_rust_funny_hamster
  QC.Ver:
    repos:
      github.com/openaire/EPrints-OAPiwik get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.olive_skeptical_cobra.sh
        container: qc.ver_paprika_cranky_nymph
timeout: 5400
